name: Workflow principal de CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build et test
        run: |
          chmod +x ./gradlew  # Donner les autorisations d'exécution si nécessaire
          bash ./gradlew build
